/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

import java.util.List;

import com.anaptecs.jeaf.core.servicechannel.api.ServiceProxy;
import com.anaptecs.jeaf.xfun.api.messages.MessageRepository;

/**
 * Remote interface for LifecycleManagerEJB.
 */
public interface LifecycleManagerEJB {
  /**
   * Method performs the initialization of JEAF. This method is intended to be called by a startup listener when the
   * application server is started.
   */
  public void initialize( );

  /**
   * Method returns the class names of all available services. The method gives clients the ability to check which of
   * the available services are usable on client side. There might be a difference between the available services on the
   * server and the support services on client side as not all classes may be available on the client.
   * 
   * @return {Vector} List with the class names of all services that are available in the server. The method never
   * returns null.
   */
  public List<String> getAllAvailableServiceNames( ) throws java.rmi.RemoteException;

  /**
   * Method returns all service proxies for the services with the passed names.
   * 
   * @param pClassnames Class names of the services that should be returned. The parameter must not be null.
   * @return Vector Method returns all services proxies for the services with the passed names. The method never returns
   * null and all object within the vector are instance of class ServiceProxy. The method returns a vector instead of a
   * collection in order to fulfill the serialization demands of the EJB standard.
   */
  public List<ServiceProxy> getServiceProxies( List<String> pClassNames ) throws java.rmi.RemoteException;

  /**
   * Method returns the message repository of the ejb container to the caller. This method is required in order to have
   * all server side messages also available on client side.
   * 
   * @return {@link MessageRepositoryImpl} Message repository with all the message objects that are loaded inside the
   * EJB container. The method never returns null.
   */
  public MessageRepository getRemoteMessageRepository( ) throws java.rmi.RemoteException;

}
