/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

/**
 * Home interface for LifecycleManagerEJB.
 */
public interface LifecycleManagerEJBHome extends javax.ejb.EJBHome {
  public static final String COMP_NAME = "java:comp/env/ejb/LifecycleManagerEJB";

  public static final String JNDI_NAME = "ejb/com/anaptecs/jeaf/1.2/LifecycleManagerEJB";

  public com.anaptecs.jeaf.core.servicechannel.ejb.api.LifecycleManagerEJB create( )
    throws javax.ejb.CreateException, java.rmi.RemoteException;

}
