/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

/**
 * Local home interface for LifecycleManagerEJB.
 */
public interface LifecycleManagerEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LifecycleManagerEJBLocal";
   public static final String JNDI_NAME="ejb/com/anaptecs/jeaf/1.2/LifecycleManagerEJBLocal";

   public com.anaptecs.jeaf.core.servicechannel.ejb.api.LifecycleManagerEJBLocal create()
      throws javax.ejb.CreateException;

}
