/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

import java.io.Serializable;

import com.anaptecs.jeaf.core.api.Service;
import com.anaptecs.jeaf.core.servicechannel.api.Command;
import com.anaptecs.jeaf.xfun.api.errorhandling.ApplicationException;
import com.anaptecs.jeaf.xfun.api.errorhandling.SystemException;
import com.anaptecs.jeaf.xfun.api.health.CheckLevel;
import com.anaptecs.jeaf.xfun.api.health.HealthCheckResult;

/**
 * Local interface for ServiceChannelEJB.
 */
public interface ServiceChannelEJBLocal extends javax.ejb.EJBLocalObject {
  static String LOCAL_EJB_JNDI_NAME =
      "java:app/jeaf-core-service-channel-ejb/ServiceChannelEJB!com.anaptecs.jeaf.core.servicechannel.ejb.api.ServiceChannelEJBLocal";

  static String EJB_LOCAL_HOME_JNDI_NAME =
      "java:app/jeaf-core-service-channel-ejb/ServiceChannelEJB!com.anaptecs.jeaf.core.servicechannel.ejb.api.ServiceChannelEJBLocalHome";

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior
   * NOT_SUPPORTED.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rolled back.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rolled back.
   */
  public Serializable executeCommandTxNotSupported( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior SUPPORTS.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rollbacked.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rollbacked.
   */
  Serializable executeCommandTxSupports( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior REQUIRED.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rollbacked.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rollbacked.
   */
  Serializable executeCommandTxRequired( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior
   * REQUIRES_NEW.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rollbacked.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rollbacked.
   */
  Serializable executeCommandTxRequiresNew( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior MANDATORY.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rollbacked.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rollbacked.
   */
  Serializable executeCommandTxMandatory( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method executes the passed command. Which actions are performed in detail depends on the service channel
   * implementation. The command may be executed within the same VM (J2SE environments) or on some remote host (J2EE
   * environments). This method call through the service channel will be executed with transaction behavior NEVER.
   * 
   * @param pCommand Command object that should be executed. The command objects contains all parameters that are
   * required to perform the corresponding service call. The parameter must not be null.
   * @return Serializable Result of the command execution. Since JEAF supports distributed environments all results must
   * be serializable.
   * @throws ApplicationException Services may throw an ApplicationException in order to indicate an application
   * specific problem.The current transaction will not be automatically rollbacked.
   * @throws SystemException Service may throw a SystemException in order to indicate technical problems. In the case of
   * an system exception the current transaction will be rollbacked.
   */
  Serializable executeCommandTxNever( Command pCommand ) throws ApplicationException, SystemException;

  /**
   * Method checks the state of the passed service. Method checks the current state of the service implementation that
   * provides the passed service interface.
   * 
   * @param pService Service whose state should be checked. The parameter must not be null.
   * @param pCheckLevel Level of check that should be performed. The parameter must not be null.
   * @return {@link HealthCheckResult} Object describing the result of the check. The method may return null. This means
   * that the service does not implement any checks.
   */
  HealthCheckResult checkService( Class<? extends Service> pServiceClass, CheckLevel pCheckLevel );

}
