/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

/**
 * Local home interface for ServiceChannelEJB.
 */
public interface ServiceChannelEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiceChannelEJBLocal";
   public static final String JNDI_NAME="ejb/com/anaptecs/jeaf/1.2/ServiceChannelEJBLocal";

   public com.anaptecs.jeaf.core.servicechannel.ejb.api.ServiceChannelEJBLocal create()
      throws javax.ejb.CreateException;

}
