/*
 * Generated by XDoclet - Do not edit!
 */
package com.anaptecs.jeaf.core.servicechannel.ejb.api;

/**
 * Home interface for ServiceChannelEJB.
 */
public interface ServiceChannelEJBHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiceChannelEJB";
   public static final String JNDI_NAME="ejb/com/anaptecs/jeaf/1.2/ServiceChannelEJB";

   public com.anaptecs.jeaf.core.servicechannel.ejb.api.ServiceChannelEJB create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
