/*
 * anaptecs GmbH, Burgstr. 96, 72764 Reutlingen, Germany
 * 
 * Copyright 2004 - 2013 All rights reserved.
 */
package com.anaptecs.jeaf.core.servicechannel.base;

import java.io.Serializable;
import java.lang.reflect.Method;

import com.anaptecs.jeaf.core.api.MessageConstants;
import com.anaptecs.jeaf.core.api.Service;
import com.anaptecs.jeaf.core.servicechannel.api.Command;
import com.anaptecs.jeaf.core.spi.ServiceImplementation;
import com.anaptecs.jeaf.xfun.api.XFun;
import com.anaptecs.jeaf.xfun.api.errorhandling.JEAFSystemException;
import com.anaptecs.jeaf.xfun.api.health.CheckLevel;
import com.anaptecs.jeaf.xfun.api.trace.Trace;

/**
 * This is a special command class as it is not generated by JEAF Generator. This command is used to perform checks of
 * the state of a service implementation. In order to achieve that for checks the same environments exists as for a
 * regular service method this command exists. This way the check can use the service channel without exposing the check
 * method to the service interface.
 */
final class CheckCommand extends Command {

  /**
   * Default serial version uid.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Constant describes the service method that is called by this proxy class.
   */
  private static final Method SERVICE_METHOD;

  static {
    try {
      SERVICE_METHOD = ServiceImplementation.class.getMethod("check", CheckLevel.class);
    }
    catch (NoSuchMethodException e) {
      throw new JEAFSystemException(MessageConstants.SERVICE_METHOD_DOES_NOT_EXIST, e,
          ServiceImplementation.class.getName(), "check(CheckLevel.class)");
    }
  }

  /**
   * Attribute transports the method parameter "pCheckLevel" to the service implementation via the service channel.
   */
  private final CheckLevel checkLevel;

  /**
   * Object array with all parameters that are passed to the service.
   */
  private final Object[] parameters;

  /**
   * Initialize object. All parameters from method "checkComponent" have to be passed as parameters to this command
   * object.
   * 
   * @param pComponentInfo ComponentInfo
   */
  CheckCommand( Class<? extends Service> pServiceClass, CheckLevel pCheckLevel ) {
    super(pServiceClass);

    checkLevel = pCheckLevel;
    parameters = new Object[] { checkLevel };
  }

  /**
   * Method executes the service call represented by this command object via JEAFs service channel.
   * 
   * @param pTargetService Reference to the service which should be called by this command. The parameter must not be
   * null.
   * @return Serializable Result object of the service call. Due to the fact that all returned objects of remote calls
   * in Java (EJBs e.g.) have to be serializable services always have to return serializable objects no matter if it
   * will be serialized or not. If a service method has no return type (void) then the method returns null. Service
   * methods also may return null as return value.
   */
  public Serializable execute( Service pTargetService ) {

    // Execute service call.
    ServiceImplementation lService = (ServiceImplementation) pTargetService;

    // Trace service call.
    Trace lTrace = XFun.getTrace();
    String lServiceName = this.getTargetServiceClass().getSimpleName();
    lTrace.write(MessageConstants.EXECUTING_SERVICE_CHECK, lServiceName);

    Serializable lResult = (Serializable) lService.check(checkLevel);

    // Trace result of service call.
    lTrace.write(MessageConstants.RETURNING_FROM_SERVICE_CHECK, lServiceName);

    return lResult;
  }

  /**
   * Method returns a method object describing the service method that will be called by this command object.
   * 
   * @return {@link Method} Method object describing the called service method. The method never returns null.
   */
  public final Method getServiceMethod( ) {
    return SERVICE_METHOD;
  }

  /**
   * Method returns all parameters that will be passed to the service.
   *
   * @return {@link Object} Object array with all parameters that will be passed to the service. The method may return
   * an empty array in case that the method has no parameters.
   */
  public Object[] getParameters( ) {
    return parameters;
  }
}
